### ISSUE TITLE
Doesn't seem to work with this UF2

### ISSUE THREAD

**Issue by cryptax** [aviciano/uf2-plugin#4]
This simple UF2 prints a simple greeting string `Hello pancake!`
I tried to use the plugin on it, but it doesn't seem to be working. Maybe I'm not using it the right way.
How do I parse the UF2?

```
$ file flag.uf2
flag.uf2: UF2 firmware image, family Raspberry Pi RP2040, address 0x10000000, 129 total blocks
$ r2 -a arm -b 16 -m 0x10000000 uf2://flag.uf2
ERROR: variable 'asm.midflags' not found
ERROR: variable 'asm.emustr' not found
ERROR: uf2: uf2families.sdb not found
```

This UF2 was created for Raspberry Pi Pico, and compiled with the pico-sdk. It runs no problem on the device.

[flag.uf2.zip](https://github.com/user-attachments/files/16026227/flag.uf2.zip)

**Comment by trufae** [comment]
@aviciano can you have a look at this?

**Comment by aviciano** [comment]
The file `uf2families.sdb` is not distributed properly. 
Changed `R_LOG_ERROR` to `R_LOG_WARN` as a temporary fix in the absence of a final solution (related to #1).

@cryptax this should work now 
```
$ r2 -a arm -b 16 uf2://flag.uf2
$ s 0x10000000
$ px
```

**Comment by trufae** [comment]
i can confirm the uf2 plugin works fine. i have compared the output with another tool that dumps into a raw file and they are 1:1 the same. so this can be closed now

**Comment by cryptax** [comment]
@aviciano thx I get `WARN: uf2: uf2families.sdb not found` but this is expected as you changed to `R_LOG_WARN` :)
